@startuml
skin rose
autonumber

actor Client as cl
participant API_Gateway as gateway
participant Server as server
participant Handler as handler
participant Controller as ctl
participant Repository as repo
database DataBase as db
participant User_Service as user
database UserDataBase as udb

activate cl
cl -> gateway : {Request}
activate gateway
alt Needs authentication
gateway -> user : Get {username + password + roles}
activate user
user -> udb : Get user
activate udb
udb --> user: {User}
deactivate udb
user --> gateway: {username + password + roles}
deactivate user
gateway -> gateway: Check user credentials
end alt
gateway -> server: {Request}
activate server
server -> handler: Handler_method()
activate handler
handler -> ctl: Controller_Method()
activate ctl
ctl -> repo: Repository_Method()
activate repo
repo -> db: GetData()
activate db
db --> repo: {Data}
deactivate db
repo --> ctl: {Promise<Data>}
deactivate repo
ctl --> handler: {Promise<Data>}
deactivate ctl
handler --> server: {HTTP Response}
deactivate handler
server --> gateway: {HTTP Response}
deactivate server
gateway --> cl: {HTTP Response}
deactivate gateway
deactivate cl
@enduml