name: Build Project
on:
  push:
    branches: 
      - develop
permissions:
  checks: write
  contents: write

jobs:
  build_backend:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout repository
      uses: actions/checkout@v4
    # get the latest commit to check the changed files
    - name: Get base commit
      run: |
        git fetch origin "${{github.head_ref || github.ref_name}}"
        base_sha=$(git rev-parse "origin/develop")
        echo "Base Sha: '${base_sha}'"
        echo "base_sha=$base_sha" >> $GITHUB_ENV
    - name: Get Backend changed files
      run: |
        echo "Base Sha: '${base_sha}'"
        changed_source_backend_files=$(git diff --name-only "$base_sha" "$GITHUB_SHA" | grep '\.cs$' || true)
        echo "Files to validate: '${changed_source_backend_files}'"
        echo "updated_files=$(echo ${changed_source_backend_files})" >> $GITHUB_ENV
    # Determine if there are changed .cs files
    - name: Check for backend changed files
      id: check_changes_cs
      run: |
        if [[ -n "$changed_source_backend_files" ]]; then
          echo "files_changed=true" >> $GITHUB_ENV
        else
          echo "files_changed=false" >> $GITHUB_ENV
        fi  
    # Linting, building, and testing the project
    - name: Setup .NET
      if: steps.check_changes_cs.outputs.files_changed == 'true'
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: 6.0.x
    - name: Run dotnet format/linter
      if: steps.check_changes_cs.outputs.files_changed == 'true'
      uses: wearerequired/lint-action@v2
      with:
        dotnet_format: true
    - name: Restore dependencies
      if: steps.check_changes_cs.outputs.files_changed == 'true'
      run: dotnet restore
    - name: Build
      if: steps.check_changes.outputs.files_changed == 'true'
      run: dotnet build --no-restore
      
      
    - name: Test
      if: steps.check_changes.outputs.files_changed == 'true'
      run: dotnet test --no-build --verbosity normal
  build_client:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout repository
      uses: actions/checkout@v4
    # get the latest commit to check the changed files
    - name: Get base commit
      run: |
        git fetch origin "${{github.head_ref || github.ref_name}}"
        base_sha=$(git rev-parse "origin/${{github.head_ref || github.ref_name}}")
        echo "base_sha=$base_sha" >> $GITHUB_ENV
    - name: Get Client changed files
      run: |
        changed_source_client_files=$(git diff-tree --no-commit-id --name-only -r "$base_sha" "$GITHUB_SHA" | { grep "**.ts$" || test $? = 1; })
        echo "Files to validate: '${changed_source_client_files}'"
        echo "updated_files=$(echo ${changed_source_client_files})" >> $GITHUB_ENV
       # Determine if there are changed .cs files
    - name: Check for backend changed files
      id: check_changes_client
      run: |
        if [[ -n "$changed_source_client_files" ]]; then
          echo "client_files_changed=true" >> $GITHUB_ENV
        else
          echo "client_files_changed=false" >> $GITHUB_ENV
        fi
   
    - name: Use Node.js ${{ matrix.node-version }}
      if: steps.check_changes_client.outputs.client_files_changed == 'true'
      uses: actions/setup-node@v3
      with:
        node-version: 18.x
        cache: 'npm'
    - name: Clean install Client Project
      if: steps.check_changes_client.outputs.client_files_changed == 'true'
      run: npm ci
    - name: Run eslint and prettier
      if: steps.check_changes_client.outputs.client_files_changed == 'true'
      uses: wearerequired/lint-action@v2
      with:
        eslint: true
        prettier: true
    - name: Build Client Project
      if: steps.check_changes_client.outputs.client_files_changed == 'true'
      run: npm run build --if-present
      

