name: Build Project
on:
  push:
    branches: 
      - develop
    paths-ignore:
      - '**/*.md'
      - '**/*.txt'
      - '**/*.pdf'
      - '**/*.puml'
      - '**/*.xlsx'
      - '**/*.drawio'
permissions:
  checks: write
  contents: write

jobs:
  build_backend:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout repository
      uses: actions/checkout@v4
      with:
        fetch-depth: 0 
    # Linting, building, and testing the project
    - name: Setup .NET
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: 6.0.x
    - name: Run dotnet format/linter
      uses: wearerequired/lint-action@v2
      with:
        dotnet_format: true
    - name: Move to Backend Folder
      run: |
        cd Backend/StreamingPlatform
    - name: Restore dependencies
      run: dotnet restore
    - name: Build
      run: dotnet build --no-restore    
    - name: Test
      run: dotnet test --no-build --verbosity normal
  build_client:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout repository
      uses: actions/checkout@v4
    - name: Move to Client Folder
      run: |
        cd Client/streaming-service
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v3
      with:
        node-version: 18.x
        cache: 'npm'
    - name: Clean install Client Project
      run: npm ci
    - name: Run eslint and prettier
      uses: wearerequired/lint-action@v2
      with:
        eslint: true
        prettier: true
    - name: Build Client Project
      run: npm run build --if-present
      

