name: Build Project
on:
  push:
    branches: 
      - develop
    paths-ignore:
      - '**/*.md'
      - '**/*.txt'
      - '**/*.pdf'
      - '**/*.puml'
      - '**/*.xlsx'
      - '**/*.drawio'
permissions:
  checks: write
  contents: write

jobs:
  build_backend:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: Backend/StreamingPlatform
    steps:
    - name: Checkout repository
      uses: actions/checkout@v4
      with:
        fetch-depth: 0 
    # building, and testing the project
    - name: Setup .NET
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: 6.0.x
    - name: Restore dependencies
      run: dotnet restore
    - name: Build
      run: dotnet build --no-restore    
    - name: Test
      run: dotnet test --no-build --verbosity normal
    - name: Format
      run: dotnet format --verify-no-changes --verbosity diagnostic
  build_client:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: Client/streaming-service
    steps:
    - name: Checkout repository
      uses: actions/checkout@v4
    - name: Use Node.js 20.x
      uses: actions/setup-node@v3
      with:
        node-version: 20.x
        cache: 'npm'
        cache-dependency-path: Client/streaming-service
    - name: Clean install Client Project
      run: npm ci
    - name: Install Angular
      run: npm install -g @angular/cli@latest 
    - name: Code Linting
      run: npm run lint
    - name: Build Client Project
      run: npm run build --if-present
      

