name: "Scan code "
on:
  pull_request:
    branches:
      - master
    paths-ignore:
      - '**/*.md'
      - '**/*.txt'
      - '**/*.pdf'
      - '**/*.puml'
      - '**/*.xlsx'
      - '**/*.drawio'
      - '**/*.yml'
    
  pull_request:
    branches:
      - master
    paths-ignore:
      - '**/*.md'
      - '**/*.txt'
      - '**/*.pdf'
      - '**/*.puml'
      - '**/*.xlsx'
      - '**/*.drawio'
      - '**/*.yml'

  schedule:
    - cron: '0 1 * * 1,5'

jobs:
  analyze:
    name: Analyze (${{ matrix.language }})
    runs-on: 'ubuntu-latest'
    timeout-minutes: 120
    permissions:
      security-events: write
      packages: read
      actions: read
      contents: read

    strategy:
      fail-fast: false
      matrix:
      # Defines the languages we want to check (csharp on the server side and typescript on the client side)
        include:
          - language: csharp
            build-mode: autobuild
          - language: javascript-typescript
            build-mode: none
          
    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Initialize CodeQL
      uses: github/codeql-action/init@v3
      with:
        languages: ${{ matrix.language }}
        build-mode: ${{ matrix.build-mode }}
        config: |
          disable-default-queries: true
          queries:
            - uses: security-extended
    - name: Perform CodeQL Analysis
      uses: github/codeql-action/analyze@v3
      with:
        category: "/language:${{matrix.language}}"
